### ISSUE TITLE
S3 Bucket interaction

### ISSUE THREAD

**Issue by gnoronha-mdsol** [rocky02/s3_store#1]
Have your code able to be able to run the following
- s3 bucket create [bucket_name]
- s3 bucket remove [bucket_name]
- s3 bucket list

Ensure that Validations are in place. Have Rspec to test all the code.
Configuration is from a YAML file similar to what was there for `q_it`.

**Comment by rocky02** [comment]
Work in PR #3

**Comment by rocky02** [comment]
Completed and merged.
